### ISSUE TITLE
Совместимость с php 5.3

### ISSUE THREAD

**Issue by OAPrilepa** [arrilot/bitrix-iblock-helper#2]
Доброго времени суток!
Насколько понимаю, для совместимости с php 5.3 достаточно в файле \bitrix-iblock-helper\src\IblockId.php в 60 строке заменить [] на Array().
Можем сделать такую правку?
А то модуль классный, но к сожалению не всегда есть возможность обновить на сервере клиента php до 5.6 и выше.

**Comment by arrilot** [comment]
Привет, нет он еще например требует arrilot/bitrix-cacher который 5.4+
Так что нет, минимальная версия пакета уменьшаться не будет.
Если прямо очень сильно хочется, то можешь форкнуть подправить всё до php 5.3 убрав кэширование и т д и использовать свой форк.

Но вообще использовать php 5.3 в 2017 году совсем печально)

**Comment by OAPrilepa** [comment]
Arrilot\BitrixCacher на 5.3 запустился без проблем;
В итоге убедили клиента, что пора обновить версию php.

На будущее, если я форкнул решение, как убедить композер, что форк приоритетней? Достаточно ли указать в секции repositories путь до форка? Или в форке нужно поправить composer.json изменив наименование пакета на своё?

**Comment by arrilot** [comment]
https://stackoverflow.com/questions/13498519/how-to-require-a-fork-with-composer

**Comment by OAPrilepa** [comment]
Благодарю, принцип понял.
